apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-keys
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: cosign-key-secret
  data:
  - secretKey: cosign.key
    remoteRef:
      key: generic/cosign/signer
      property: cosign.key
