apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-docker-external
  namespace: tekton-pipelines
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: SecretStore
  target:
    name: cosign-docker-secret-capten-pipeline
  data:
  - secretKey: password
    remoteRef:
      key: generic/container-registry/5c577dc2-6a99-42df-b493-99f7d44efa9e
      property: password
  - secretKey: username
    remoteRef:
      key: generic/container-registry/5c577dc2-6a99-42df-b493-99f7d44efa9e
      property: username
