apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-keys
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: SecretStore
  target:
    name: cosign-keys
  data:
  - secretKey: cosign.key
    remoteRef:
      key: generic/cosign/signer
      property: cosign.key
  - secretKey: cosign.pub
    remoteRef:
      key: generic/cosign/signer
      property: cosign.pub