apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    tekton.dev/git-0: "https://github.com"
  name: docker-external
  namespace: tekton-pipelines
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: SecretStore
  target:
    name: docker-credentials-capten-pipeline
  data:
  - secretKey: config.json
    remoteRef:
      key: generic/container-registry/5c577dc2-6a99-42df-b493-99f7d44efa9e
      property: config.json
