apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extraconfig-external
  namespace: tekton-pipelines
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: SecretStore
  target:
    name: extraconfig-capten-pipeline
  data:
  - secretKey: GIT_TOKEN
    remoteRef:
      key: generic/git-project/8f6be4b4-f1f2-4c3f-96b6-dc96b9e66209
      property: accessToken
  - secretKey: GIT_USER_NAME
    remoteRef:
      key: generic/git-project/8f6be4b4-f1f2-4c3f-96b6-dc96b9e66209
      property: userID

