apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    tekton.dev/git-0: "https://github.com"
  name: gitcred-external
  namespace: tekton-pipelines
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: SecretStore
  target:
    name: gitcred-capten-pipeline
  data:
  - secretKey: password
    remoteRef:
      key: generic/git-project/cbacb842-9cff-472c-bd14-96bc375e0713
      property: accessToken
  - secretKey: username
    remoteRef:
      key: generic/git-project/cbacb842-9cff-472c-bd14-96bc375e0713
      property: userID
