apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-dev-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/intelops/capten-templates.git
    targetRevision: main
    path: crossplane/crossplane-config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
