apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/intelops/capten-templates.git
    targetRevision: HEAD
    path: argocd/apps/clusters
    helm
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
